openapi: 3.0.3

info:
  title: ShukatsuLog API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル環境

paths:
  /api/login:
    $ref: ./auth/login.yaml
  /api/token/refresh:
    $ref: ./auth/token.refresh.yaml
  /api/logout:
    $ref: ./auth/logout.yaml

  /api/user:
    $ref: ./user/user.yaml

  /api/event:
    $ref: ./event/event.yaml
  /api/event/{event_id}:
    $ref: ./event/event.event_id.yaml

  /api/company:
    $ref: ./company/company.yaml
  /api/company/{company_id}:
    $ref: ./company/company.company_id.yaml

  /api/apply/status-summary:
    $ref: ./apply/apply.status-summary.yaml
  /api/apply:
    $ref: ./apply/apply.yaml
  /api/apply/{apply_id}:
    $ref: ./apply/apply.apply_id.yaml
  /api/apply/{apply_id}/document:
    $ref: ./apply/apply.apply_id.document.yaml
  /api/apply/{apply_id}/document/{document_id}:
    $ref: ./apply/apply.apply_id.document.document_id.yaml
  /api/apply/{apply_id}/document/{document_id}/file/{file_id}:
    $ref: ./apply/apply.apply_id.document.document_id.file.file_id.yaml
  /api/apply/{apply_id}/exam:
    $ref: ./apply/apply.apply_id.exam.yaml
  /api/apply/{apply_id}/exam/{exam_id}:
    $ref: ./apply/apply.apply_id.exam.exam_id.yaml
  /api/apply/{apply_id}/interview:
    $ref: ./apply/apply.apply_id.interview.yaml
  /api/apply/{apply_id}/interview/{interview_id}:
    $ref: ./apply/apply.apply_id.interview.interview_id.yaml
  /api/apply/{apply_id}/offer:
    $ref: ./apply/apply.apply_id.offer.yaml
  /api/apply/{apply_id}/offer/{offer_id}:
    $ref: ./apply/apply.apply_id.offer.offer_id.yaml
  /api/apply/{apply_id}/final_result:
    $ref: ./apply/apply.apply_id.final_result.yaml
  /api/apply/{apply_id}/final_result/{final_result_id}:
    $ref: ./apply/apply.apply_id.final_result.final_result_id.yaml
  /api/apply/{apply_id}/process:
    $ref: ./apply/apply.apply_id.process.yaml

components:
  schemas:
    AuthInfo:
      $ref: ./schemas/auth/AuthInfo.yaml
    User:
      $ref: ./schemas/users/User.yaml
    Event:
      $ref: ./schemas/events/Event.yaml
    Company:
      $ref: ./schemas/companies/Company.yaml
    Apply:
      $ref: ./schemas/applies/Apply.yaml
    Document:
      $ref: ./schemas/applies/process/Document.yaml
    File:
      $ref: ./schemas/applies/process/File.yaml
    Exam:
      $ref: ./schemas/applies/process/Exam.yaml
    Interview:
      $ref: ./schemas/applies/process/Interview.yaml
    Offer:
      $ref: ./schemas/applies/process/Offer.yaml
    FinalResult:
      $ref: ./schemas/applies/process/FinalResult.yaml

    BadRequestResponse:
      $ref: ./schemas/error/BadRequestResponse.yaml
    UnauthorizedResponse:
      $ref: ./schemas/error/UnauthorizedResponse.yaml
    InternalServerErrorResponse:
      $ref: ./schemas/error/InternalServerErrorResponse.yaml

  securitySchemes:
    BearerAuth:
      $ref: ./security-schemes/BearerAuth.yaml
