openapi: 3.0.3

info:
  title: ShukatsuLog API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル環境

paths:
  /api/user:
    $ref: ./user/user.yaml

  /api/event:
    $ref: ./event/event.yaml

components:
  securitySchemes:
    BearerAuth:
      $ref: ./security-schemes/BearerAuth.yaml
