openapi: 3.0.3

info:
  title: ShukatsuLog API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル環境

paths:
  /api/user:
    $ref: ./user/user.yaml

  /api/event:
    $ref: ./event/event.yaml
  /api/event/{event_id}:
    $ref: ./event/event.event_id.yaml

components:
  schemas:
    User:
      $ref: ./schemas/users/User.yaml
    Event:
      $ref: ./schemas/events/Event.yaml

    BadRequestResponse:
      $ref: ./schemas/error/BadRequestResponse.yaml
    UnauthorizedResponse:
      $ref: ./schemas/error/UnauthorizedResponse.yaml
    InternalServerErrorResponse:
      $ref: ./schemas/error/InternalServerErrorResponse.yaml

  securitySchemes:
    BearerAuth:
      $ref: ./security-schemes/BearerAuth.yaml
