openapi: 3.0.3

info:
  title: ShukatsuLog API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル環境

paths:
  /api/user:
    $ref: ./user/user.yaml

  /api/event:
    $ref: ./event/event.yaml
  /api/event/{event_id}:
    $ref: ./event/event.event_id.yaml

  /api/company:
    $ref: ./company/company.yaml
  /api/company/{company_id}:
    $ref: ./company/company.company_id.yaml

  /api/apply/status-summary:
    $ref: ./apply/apply.status-summary.yaml
  /api/apply:
    $ref: ./apply/apply.yaml
  /api/apply/{apply_id}:
    $ref: ./apply/apply.apply_id.yaml

components:
  schemas:
    User:
      $ref: ./schemas/users/User.yaml
    Event:
      $ref: ./schemas/events/Event.yaml
    Company:
      $ref: ./schemas/companies/Company.yaml
    Apply:
      $ref: ./schemas/applies/Apply.yaml

    BadRequestResponse:
      $ref: ./schemas/error/BadRequestResponse.yaml
    UnauthorizedResponse:
      $ref: ./schemas/error/UnauthorizedResponse.yaml
    InternalServerErrorResponse:
      $ref: ./schemas/error/InternalServerErrorResponse.yaml

  securitySchemes:
    BearerAuth:
      $ref: ./security-schemes/BearerAuth.yaml
