name: Test

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_shukatsu_log
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Copy .env.testing
        run: cp .env.testing .env
      - name: Run Migrations
        run: php artisan migrate --force
      - name: Check tables in DB
        run: mysql -hdb -P3306 -uroot -proot -e "SHOW TABLES IN test_shukatsu_log;"
